#机器人微信nickName
bot:
  botName: 黄色方块
  wechat.qrcode.path: D:/test
  openai.completio.model: text-davinci-003
  openai.completio.temperature: 0.9
  openai.completio.max_tokens: 2000
  openai.completio.top_p: 1
  openai.completio.frequency_penalty: 0.0
  openai.completio.presence_penalty: 0.6
  openai.completio.stop:
  workspace: D:/botSpace
  apikey: 0abfd5005885953a328d93d2355bbb77
  #获取新闻的群聊
  newsgroup: 测试小组
server:
  port: 4433


spring:
  task:
    scheduling:
      pool:
        size: 8
  datasource:
    url: jdbc:mysql://107.151.239.215:3306/chat?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 5795583
    hikari:
      minimum-idle: 5
      maximum-pool-size: 80
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
